version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
    restart: always
    command: bash -c 'nginx -g "daemon off;"'

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
