name: 'Chromatic Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-chromatic-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install ci
        working-directory: ./client
      - name: Build storybook
        uses: chromaui/action@v1
        with:
          workingDir: client
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
